config/routes.rb
Rails.application.routes.draw do
  resources :eras
  
  root "eras#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/era.rb
class Era < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/eras_controller.rb
class ErasController < ApplicationController
  before_action :set_era, only: [:show, :edit, :update, :destroy]

  # GET /eras
  # GET /eras.json
  def index
    @eras = Era.all
  end

  # GET /eras/1
  # GET /eras/1.json
  def show
  end

  # GET /eras/new
  def new
    @era = Era.new
  end

  # GET /eras/1/edit
  def edit
  end

  # POST /eras
  # POST /eras.json
  def create
    @era = Era.new(era_params)

    respond_to do |format|
      if @era.save
        format.html { redirect_to @era, notice: 'Era was successfully created.' }
        format.json { render :show, status: :created, location: @era }
      else
        format.html { render :new }
        format.json { render json: @era.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eras/1
  # PATCH/PUT /eras/1.json
  def update
    respond_to do |format|
      if @era.update(era_params)
        format.html { redirect_to @era, notice: 'Era was successfully updated.' }
        format.json { render :show, status: :ok, location: @era }
      else
        format.html { render :edit }
        format.json { render json: @era.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eras/1
  # DELETE /eras/1.json
  def destroy
    @era.destroy
    respond_to do |format|
      format.html { redirect_to eras_url, notice: 'Era was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_era
      @era = Era.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def era_params
      params.require(:era).permit(:title, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eras_helper.rb
module ErasHelper
end

app/views/eras/_form.html.erb
<%= form_with(model: era, local: true) do |form| %>
  <% if era.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(era.errors.count, "error") %> prohibited this era from being saved:</h2>

      <ul>
      <% era.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :era_title %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time, id: :era_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/eras/edit.html.erb
<h1>Editing Era</h1>

<%= render 'form', era: @era %>

<%= link_to 'Show', @era %> |
<%= link_to 'Back', eras_path %>

app/views/eras/index.html.erb
<div class="container">
  <h1>Important Eras of Human History</h1>
</div>

<a href="#">
<div class="column">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail cold">
      <img class="photo"src="http://cmsmcgregor.weebly.com/uploads/5/9/0/7/59073555/4349262_orig.jpg" alt="1945-1991">
      <div class="caption">
        <h3>Cold War</h3>
        <p>1945-1991</p>
      </div>
    </div>
  </div>
</div>
</a>
<a href="#">
<div class="column">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail cold">
      <img class="photo"src="https://archive.is/qPtXJ/cec0f8b4b564e9e42f350ce534dada4c3e6525ab.jpg" alt="1945-1991">
      <div class="caption">
        <h3>WW2</h3>
        <p>1939-1945</p>
      </div>
    </div>
  </div>
</div>
</a>
<a href="#">
<div class="column">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail cold">
      <img class="photo"src="http://data.whicdn.com/images/13470710/tumblr_lq1i87dvEI1qf0ksao1_500_large.jpg" alt="1945-1991">
      <div class="caption">
        <h3>Interwar period</h3>
        <p>1919-1939</p>
      </div>
      <p>Includes Spanish Civil War, Japanese invasion of Manchuria, Rise of Fasicm, Great Purge</p>
    </div>
  </div>
</div>
</a>
<a href="#">
<div class="column">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail cold">
      <img class="photo"src="https://worldwaripropaganda.files.wordpress.com/2011/01/world-war-1-propaganda1.jpg">
      <div class="caption">
        <h3>WW1</h3>
        <p>1914-1918</p>
      </div>
      <p>Includes Western Front, fall of Empires</p>
    </div>
  </div>
</div>
</a>
<a href="#">
<div class="column">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail cold">
      <img class="photo"src="https://upload.wikimedia.org/wikipedia/commons/1/17/Wernerprokla.jpg" alt"The coronation of Wilhelm I">
      <div class="caption">
        <h3>Before the Great War</h3>
        <p>1871-1914</p>
      </div>
      <p>Includes: Balkan Wars, Chinese Revolution, Russian Revolution 1905, Roald Amundsen's Dicsovery of South Pole, Fridtjof Nansen's crossing of Greenland</p>
    </div>
  </div>
</div>
</a>
<a href="#">
<div class="column">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail cold">
      <img class="photo"src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg/250px-Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg" alt"Liberty leading the People">
      <div class="caption">
        <h3>Rise of Nationalism and Liberalism</h3>
        <p>1815-1871</p>
      </div>
         <p>Includes: Congress of Vienna, Revolution of 1830, Revolution of 1848, Crimean War, Unification of Germany and Italy</p>
    </div>
  </div>
</div>
</a>
<a href="#">
<div class="column">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail cold">
     <img class="photo"src="https://upload.wikimedia.org/wikipedia/commons/0/08/Jacques-Louis_David%2C_The_Coronation_of_Napoleon_edit.jpg" alt"Coronation of Napoleon Bonaparte">
      <div class="caption">
        <h3>Napoleonic Era</h3>
        <p>1799-1815</p>
      </div>
        <p>Includes: Coup of Brumaire, The Coalitions, Peninsular War, Continental System, Invasion of Russia, Hundred Days</p>
    </div>
  </div>
</div>
</a>
<!-- Old text under Here -->
<p id="notice"><%= notice %></p>

<h1>Eras</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eras.each do |era| %>
      <tr>
        <td><%= era.title %></td>
        <td><%= era.time %></td>
        <td><%= link_to 'Show', era %></td>
        <td><%= link_to 'Edit', edit_era_path(era) %></td>
        <td><%= link_to 'Destroy', era, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Era', new_era_path %>

app/views/eras/new.html.erb
<h1>New Era</h1>

<%= render 'form', era: @era %>

<%= link_to 'Back', eras_path %>

app/views/eras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @era.title %>
</p>

<p>
  <strong>Time:</strong>
  <%= @era.time %>
</p>

<%= link_to 'Edit', edit_era_path(@era) %> |
<%= link_to 'Back', eras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("bygone.png", :alt => "bygone logo", height: 35) %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Contact us <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Shop</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Cold War</a></li>
            <li><a href="#">WW2</a></li>
            <li><a href="#">Interwar period</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Resources</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Links</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">My account</a></li>
            <li><a href="#">Login</a></li>
            <li><a href="#">Create an account</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <title>Bygone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>